### PR TITLE
White: Add lavender

### PR DESCRIPTION
**Pull request by Canary233**
Coolapk Release link:
https://www.coolapk.com/feed/34038617?shareKey=YTEzOWIxZWYyNTgzNjIyNDNkMWQ~&shareUid=1831662&shareFrom=com.coolapk.market_12.0.0-beta6

SELinux:
Enforcing

Igore neverallows flag:
false

CTS Status:
Passed

Issues:

Unknown

Kernel Source:
https://github.com/Canary-Buildbot/android_kernel_xiaomi_lavender

Device Source:
https://github.com/Canary-Buildbot/android_device_xiaomi_lavender

Vendor Blobs:
https://github.com/Canary-Buildbot/android_vendor_xiaomi_lavender

Wanna say something? :
Merge https://github.com/Project-Mushroom/platform_bionic/pull/1 please

### CODE REVIEW

**Comment by AmeChanRain** [comment]
Sorry... ify-only device is strictly forbidden in our device repo.
And please check
https://github.com/Project-Mushroom/platform_manifest/wiki

**Comment by AmeChanRain** [comment]
Hope one day you could be a part of us, cheer!
OvO

**Comment by Canary233** [comment]
> 

Thinks! I will work harder>_<

**Comment by AmeChanRain** [comment]
Also, please check this
https://github.com/Project-Mushroom/platform_manifest/blob/snow/READMECN.md?plain=1#L125

Sorry for annoying, have a nice day (◍•ᴗ•◍)❤

**Pull request closed without merging**
