### PR TITLE
White: Add sagit

### PR DESCRIPTION
**Pull request by Nanhumly**
Coolapk link:
https://www.coolapk.com/feed/49263443?shareKey=NWYyZWI0ZWY2YTg0NjUwMDcwOGE~&shareUid=2342921&shareFrom=com.coolapk.market_13.3.1

TG channel Link:
https://t.me/sagitupdate/2209

SELinux:
Enforcing

Igore neverallows flag:
false

CTS Status:
Passed

Issues:
1.Prompt for vendor interface incompatibility after booting the device
2.Button backlight

Device Source:
https://github.com/Nanhumly/android_device_xiaomi_sagit
https://github.com/Nanhumly/android_device_xiaomi_msm8998-common

Vendor Blobs:
https://github.com/Nanhumly/proprietary_vendor_xiaomi_sagit
https://github.com/Nanhumly/proprietary_vendor_xiaomi_msm8998-common

Kernel Source:
https://github.com/Nanhumly/android_kernel_xiaomi_msm8998

Source Patch:
Nanhumly/platform_frameworks_base@f836cc0
Nanhumly/platform_frameworks_base@0b79df9
Nanhumly/platform_frameworks_opt_telephony@b8a42de

Wanna say something? :
Thank you for letting me learn a lot~

### CODE REVIEW

**Comment by AmeChanRain** [comment]
Maybe you could merge it since we only have sagit support?
Anyway it's fine to separate it, but I'm prefer to merge it into one.
That's okay if you disagree.
Waiting for your reply! :3

**Comment by Nanhumly** [comment]
> Maybe you could merge it since we only have sagit support? Anyway it's fine to separate it, but I'm prefer to merge it into one. That's okay if you disagree. Waiting for your reply! :3

I'd like to keep it separate as I'd like to add support for chiron in the future ❤️.

**Comment by AmeChanRain** [comment]
Okay, welcome to Miku UI. (*^_^*)
Source patches will apply later!
Let's create new repos and server scripts for you!
Once everything is done, this PR will be merged.

**Comment by AmeChanRain** [comment]
https://github.com/Nanhumly/platform_frameworks_base/commit/f836cc0
We really need that patch? I think we **should** warn users if there's fingerprint mismatch.
Anything breaks on sagit without this patch?

**Comment by Nanhumly** [comment]
> [Nanhumly/platform_frameworks_base@f836cc0](https://github.com/Nanhumly/platform_frameworks_base/commit/f836cc0) We really need that patch? I think we **should** warn users if there's fingerprint mismatch. Anything breaks on sagit without this patch?

Every time the device starts on sagit, a reminder will appear: There is an internal problem with your device. Please contact your device manufacturer for details. But this won't actually cause other problems.

**Comment by AmeChanRain** [comment]
> > [Nanhumly/platform_frameworks_base@f836cc0](https://github.com/Nanhumly/platform_frameworks_base/commit/f836cc0) We really need that patch? I think we **should** warn users if there's fingerprint mismatch. Anything breaks on sagit without this patch?
> 
> Every time the device starts on sagit, a reminder will appear: There is an internal problem with your device. Please contact your device manufacturer for details. But this won't actually cause other problems.

Well, then I guess we should keep it as before since this commit is more like a HACK. It will affect other official devices (we should warn users if there's fingerprint mismatch). 😉

**Comment by AmeChanRain** [comment]
Patches set! Please edit your device configurations(e.g. add miku.dependencies) and push it to official device repos.

**Comment by Nanhumly** [comment]
> > > [Nanhumly/platform_frameworks_base@f836cc0](https://github.com/Nanhumly/platform_frameworks_base/commit/f836cc0) We really need that patch? I think we **should** warn users if there's fingerprint mismatch. Anything breaks on sagit without this patch?
> > 
> > 
> > Every time the device starts on sagit, a reminder will appear: There is an internal problem with your device. Please contact your device manufacturer for details. But this won't actually cause other problems.
> 
> Well, then I guess we should keep it as before since this commit is more like a HACK. It will affect other official devices (we should warn users if there's fingerprint mismatch). 😉

Okay, I will look for the right way to solve it.

**Comment by Nanhumly** [comment]
> Patches set! Please edit your device configurations(e.g. add miku.dependencies) and push it to official device repos.

Done 😃

**Pull request merged**
